# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dbb38be31575d41009deffe47c326d7a"
name = "my-test-app"
application_url = "https://both-das-ri-buyers.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-1ed633b0.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://both-das-ri-buyers.trycloudflare.com/auth/callback",
  "https://both-das-ri-buyers.trycloudflare.com/auth/shopify/callback",
  "https://both-das-ri-buyers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
